apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-cd-sample
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: ci-cd-sample
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: ci-cd-sample
        image: eosityk8s.azurecr.io/ci-cd-sample:0.0.6-SNAPSHOT
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-sample
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ci-cd-sample
